services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

    volumes:
      - .:/app
      - react-app-node-modules:/app/node_modules

volumes:
  react-app-node-modules:
